#!/bin/bash -x
#TODO make dev folder a variable
cp ../UI-dev3.0vite/standalone.env.production ../UI-dev3.0vite/.env.production
cd ../UI-dev3.0vite
pwd
ls -ltra
rm -fr dist node_modules
npm i
vite build
cd ..
pwd
rm -fr standalone/vulcan
mv UI-dev3.0vite/dist standalone/vulcan
echo "Installing with default composer. If you added plugins which require changes to composer, Replace composer.json with your own composer.json, and re-run this script."
rm -fr vendor composer.lock composer.json
echo "If there is a composer.json.private, using that. Otherwise using composer.json.default"
if [ -e ./composer.json.private ]; then
    echo "identified a private json file, using that"
    cp ./composer.json.private ./composer.json
else
    echo "Using default composer.json"
    cp ./composer.json.default ./composer.json
fi
composer u -o --no-dev

cd standalone
pwd
./kickbutt.sh
