#!/bin/bash -x
#TODO make dev folder a variable
cp ../UI-dev3.0/standalone.env.production ../UI-dev3.0/.env.production
cd ../UI-dev3.0
pwd
ls -ltra
rm -fr build node_modules
npm i
npm run build
cd ..
pwd
rm -fr standalone/vulcan
mv UI-dev3.0/build standalone/vulcan
echo "Installing with default composer. If you added plugins which require changes to composer, Replace composer.json with your own composer.json, and re-run this script."
rm -fr vendor composer.lock
composer u -o --no-dev
cd standalone
pwd
./kickbutt.sh
